### ISSUE TITLE
Can't play MP3

### ISSUE THREAD

**Issue by danielktaylor** [tbowmo/chromecastcontrol#46]
Sending:

* Topic: `chromecast/kitchen/control/play`
* Payload: `{ "link": "http://192.168.1.109:1300/music.mp3", "type": "audio/mp3" }`

Results in:

```
2023-09-11 22:51:30,328 mqtt             DEBUG    Received PUBLISH (d0, q0, r0, m0), 'chromecast/kitchen/control/play', ...  (73 bytes)
2023-09-11 22:51:30,328 pychromecast     INFO     Quitting current app
2023-09-11 22:51:30,328 pychromecast.controllers INFO     Receiver:Stopping current app 'None'
2023-09-11 22:51:30,329 pychromecast.socket_client DEBUG    [Kitchen Google Home(192.168.1.198):8009] Sending: Message urn:x-cast:com.google.cast.receiver from sender-0 to receiver-0: {'type': 'STOP', 'requestId': 10, 'sessionId': None}
2023-09-11 22:51:30,337 pychromecast.socket_client DEBUG    [Kitchen Google Home(192.168.1.198):8009] Received: Message urn:x-cast:com.google.cast.receiver from receiver-0 to sender-0: {'requestId': 10, 'status': {'userEq': {'high_shelf': {'frequency': 4500.0, 'gain_db': 0.0, 'quality': 0.707}, 'low_shelf': {'frequency': 150.0, 'gain_db': 0.0, 'quality': 0.707}, 'max_peaking_eqs': 0, 'peaking_eqs': []}, 'volume': {'controlType': 'master', 'level': 0.20999999344348907, 'muted': False, 'stepInterval': 0.019999999552965164}}, 'type': 'RECEIVER_STATUS'}
2023-09-11 22:51:30,337 pychromecast.controllers DEBUG    Received status: CastStatus(is_active_input=None, is_stand_by=None, volume_level=0.20999999344348907, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='', icon_url=None, volume_control_type='master')
2023-09-11 22:51:30,337 chromevent_audio_kitchen_google_home INFO     CastStatus(is_active_input=None, is_stand_by=None, volume_level=0.20999999344348907, volume_muted=False, app_id=None, display_name=None, namespaces=[], session_id=None, transport_id=None, status_text='', icon_url=None, volume_control_type='master')
2023-09-11 22:51:30,338 mqtt             DEBUG    Sending PUBLISH (d0, q0, r1, m9), 'b'chromecast/kitchen/device'', ... (6 bytes)
2023-09-11 22:51:30,338 chromevent_audio_kitchen_google_home INFO     Success
2023-09-11 22:51:30,841 mqtt             DEBUG    Caught exception in user defined callback function __mqtt_action: 'audio'

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3327, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3556, in _handle_on_message
    callback(self, self._userdata, message)
  File "/usr/src/app/chrome2mqtt/devicecoordinator.py", line 44, in __mqtt_action
    room.action(command, parameter)
  File "/usr/src/app/chrome2mqtt/roomstate.py", line 106, in action
    self.__devices[device].action('play', parameter)
KeyError: 'audio'

2023-09-11 22:51:50,285 pychromecast.dial DEBUG    Resolved service ServiceInfo(type='host', data=('192.168.1.198', 8009)) to 192.168.1.198
2023-09-11 22:51:50,371 pychromecast.dial DEBUG    Resolved service ServiceInfo(type='host', data=('192.168.1.198', 8009)) to 192.168.1.198
```

Changing the volume however **does** work:

* Topic: `chromecast/kitchen/control/volume`
* Payload: `30`

**Comment by tbowmo** [comment]
What kind of chromecast devices do you have in your setup (types, numbers of devices etc)?

Also, what is your startup parameters for chrome2mqtt?

I do have a hunch where to look, but I need a bit more info, and might not be able to test things locally..

**Comment by danielktaylor** [comment]
I have two Google Home Mini devices, one of which is offline (may or may not be relevant?).

I can help test changes.

**Comment by tbowmo** [comment]
Located the culprit, could you try starting it in "standalone" mode? (adding `-S` to the startup options)

I _think_ you have started chrome2mqtt in standard mode, which assumes a couple of things in your setup, like a specific naming convention for your chromecast devices, ref [this readme](https://github.com/tbowmo/chrome2mqtt#rooms-or-single-devices) section.

the standard mode assumes that you have a standard (video) chromecast, and an audio chromecast, which is named as an example `livingroom_tv` and `livingroom_audio` when you send an link with type "audio.*" it tries to figure out the _audio device, which fails in your case.

**Comment by tbowmo** [comment]
@danielktaylor could you try the fix in #47 ?

**Comment by danielktaylor** [comment]
That commit fixes it for me @tbowmo!

**Comment by tbowmo** [comment]
Still I think you should run it with -S option (standalone), as the standard operation is meant for rooms where you have two cast devices, one for video and one for audio. As mentioned in the readme
